### PR TITLE
Fix wrong bugs controller parent class.

### PR DESCRIPTION
**Pull request by pilona**

### CODE REVIEW

**Comment by damianpolan** [comment]
Will this piece of code in bugs controller still work?

def index
    # we only update when the page is actually requested
    **update_contributors @repo.repo_path
    update_issues @repo.repo_path**
...

**Comment by pilona** [comment]
No, but it's luck that it worked in the first place, since all the `init_resouces` code in the parent operates under different assumptions. Yes, we need integration and controller unit tests now to test this stuff.

The code is in the wrong place anyway. It should have been in the model.

**Comment by damianpolan** [comment]
Okay. We just need those two lines to be guaranteed called on the following events:
-> manage page is requested
-> score page is requested

**Comment by damianpolan** [comment]
Need to refactor before solving this issue

**Pull request closed without merging**
